<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'avatar_id'=>'abc.jpg',
            'name' => 'Ravihari',
            'fname' => 'Iresha',
            'mname' => 'Ravihari',
            'lname' => 'Gamage',
            'email' => 'rig@acche.lk',
            'password' => Hash::make('Secret&Secret'),
            'NIC'=>'905183931V',
            'current_job_position'=>'chief executive officer',
            'birthday'=>'1990-08-10',
            'anniversary'=>'2017-07-14',
            'phone_home'=>'0114896289',
            'phone_mobile'=>'0754896289',
            'address_permanent'=>'No:12,Old road,Nawinna,Maharagama',
            'branch'=>'Maharagama',
            'department'=>'HR',
            'bank'=>'Commercial Bank of Ceylon PLC',
            'bank_branch'=>'Maharagama',
            'bank_number'=>'3006655229',
            'EPF_number'=>'87154ASDFRG54FD54ED',
            'next_kin_name'=>'Jayanath Gamage',
            'next_kin_occupation'=>'UI developer',
            'next_kin_office_address'=>'GreenIT Pvt. Ltd.',
            'next_kin_phone_mobile'=>'0754897289',
            'next_kin_phone_home'=>'0114896289',
            'next_kin_address'=>'No:12,Old road,Nawinna,Maharagama',
            'user_role'=>'manager',
            'supervisor_manager'=>'1',
            'created_at' => now(),
            'updated_at' => now()
        ]);
    
    DB::table('users')->insert([
            'avatar_id'=>'abc1.jpg',
            'name' => 'nathasha',
            'fname' => 'Gauri',
            'mname' => 'Nathasha',
            'lname' => 'Kularathna Arachhige ',
            'email' => 'gnku@acche.lk',
            'password' => Hash::make('Secret&Secret'),
            'NIC'=>'896943981V',
            'current_job_position'=>'Branch Manager-Maharagama branch',
            'birthday'=>'1989-07-14',
            'anniversary'=>'2013-08-10',
            'phone_home'=>'0114887689',
            'phone_mobile'=>'0754322289',
            'address_permanent'=>'No:112/A,Kosnathota,Godakawela',
            'address_temporary'=>'No:11/A,Railway road,Nawinna,Maharagama',
            'branch'=>'Maharagama',
            'department'=>'HR',
            'bank'=>'Bank of Ceylon',
            'bank_branch'=>'Godakawela',
            'bank_number'=>'3906655229',
            'EPF_number'=>'87154ASDFRG2W2E4ED',
            'next_kin_name'=>'Dissanayaka Korale Madushka Kularathna Bandara Dissanayaka',
            'next_kin_occupation'=>'Production And Quality Manager',
            'next_kin_office_address'=>'QIMA, Colombo',
            'next_kin_phone_mobile'=>'0714198811',
            'next_kin_phone_home'=>'0114887689',
            'next_kin_address'=>'No:112/A,Kosnathota,Godakawela',
            'user_role'=>'manager',
            'supervisor_manager'=>'1',
            'created_at' => now(),
            'updated_at' => now()
        ]);
    
        DB::table('users')->insert([
            'avatar_id'=>'pqr.jpg',
            'name' => 'Rukshan',
            'fname' => 'Rukshan',
            'mname' => 'Madura',
            'lname' => 'Perera',
            'email' => 'rmp@acche.lk',
            'password' => Hash::make('Secret&Secret'),
            'NIC'=>'931893932V',
            'current_job_position'=>'HR manager',
            'birthday'=>'1993-07-09',
            'phone_home'=>'0114336289',
            'phone_mobile'=>'0754336289',
            'address_permanent'=>'No:21/A,Madapatha road,Gampaha',
            'address_temporary'=>'No:52,Old road,Udahamulla,Maharagama',
            'branch'=>'Maharagama',
            'department'=>'HR',
            'bank'=>'Commercial Bank of Ceylon PLC',
            'bank_branch'=>'Gampaha',
            'bank_number'=>'3006651129',
            'EPF_number'=>'87954ASDFRG54FD54ED',
            'next_kin_name'=>'Amani Perera',
            'next_kin_occupation'=>'Teacher',
            'next_kin_office_address'=>'Central College,Gampaha',
            'next_kin_phone_mobile'=>'0774896333',
            'next_kin_phone_home'=>'0114336289',
            'next_kin_address'=>'No:21/A,Madapatha road,Gampaha',
            'user_role'=>'admin',
            'supervisor_manager'=>'2',
            'created_at' => now(),
            'updated_at' => now()
        ]);
       
     
    
     DB::table('users')->insert([
            'avatar_id'=>'pqr1.jpg',
            'name' => 'Lal',
            'fname' => 'Lal',
            'mname' => 'Srinath',
            'lname' => 'Hettipola',
            'email' => 'lsh@acche.lk',
            'password' => Hash::make('Secret&Secret'),
            'NIC'=>'731903934V',
            'current_job_position'=>'Visa counselor',
            'birthday'=>'1973-07-10',
            'anniversary'=>'1997-07-12',
            'phone_home'=>'0113654934',
            'phone_mobile'=>'0724663489',
            'address_permanent'=>'No:154/B,Peters avenue,Maradana,Colombo 4',
            'branch'=>'Maharagama',
            'department'=>'HR',
            'bank'=>'National Savings Bank',
            'bank_branch'=>'Maradana',
            'bank_number'=>'8006651129',
            'EPF_number'=>'87954ASDFRGASAS54ED',
            'next_kin_name'=>'Anjalin Christina Peiris',
            'next_kin_phone_mobile'=>'0724357689',
            'next_kin_phone_home'=>'0114114545',
            'next_kin_address'=>'No:154/B,Peters avenue,Maradana,Colombo 4',
            'user_role'=>'employee',
            'supervisor_manager'=>'2',
            'created_at' => now(),
            'updated_at' => now()
        ]);
    
     DB::table('users')->insert([
            'avatar_id'=>'pqr2.jpg',
            'name' => 'Bamunu',
            'fname' => 'Bamunu',
            'lname' => 'Wanigasuriya',
            'email' => 'bw@acche.lk',
            'password' => Hash::make('Secret&Secret'),
            'NIC'=>'981913934V',
            'current_job_position'=>'Visa counselor',
            'birthday'=>'1998-07-11',
            'anniversary'=>'1997-07-11',
            'phone_home'=>'0113348934',
            'phone_mobile'=>'0774823489',
            'address_permanent'=>'No:14/B,Abagaha Handiya,Galenbidunuwawa,Anuradapura',
            'address_temporary'=>'No:52,Old road,Udahamulla,Maharagama',
            'branch'=>'Maharagama',
            'department'=>'HR',
            'bank'=>'Sampath Bank PLC',
            'bank_branch'=>'Anuradapura',
            'bank_number'=>'8013651129',
            'EPF_number'=>'87954AKSFRG5K4K64ED',
            'next_kin_name'=>'Sriyani Bandara',
            'next_kin_phone_mobile'=>'0714346289',
            'next_kin_phone_home'=>'0113348934',
            'next_kin_address'=>'No:14/B,Abagaha Handiya,Galenbidunuwawa,Anuradapura',
            'user_role'=>'employee',
            'supervisor_manager'=>'2',
            'created_at' => now(),
            'updated_at' => now()
        ]);
    
    DB::table('users')->insert([
            'avatar_id'=>'abc2.jpg',
            'name' => 'shadi',
            'fname' => 'Shadi',
            'mname' => 'Jeevansathi',
            'lname' => ' Maniratnam',
            'email' => 'sjm@acche.lk',
            'password' => Hash::make('Secret&Secret'),
            'NIC'=>'916923981V',
            'current_job_position'=>'Visa counselor',
            'birthday'=>'1991-07-12',
            'anniversary'=>'2013-07-10',
            'phone_home'=>'0114897689',
            'phone_mobile'=>'0754336289',
            'address_permanent'=>'No:112,Fife road,Thimbirigasyaya,Colombo 03',
            'branch'=>'Maharagama',
            'department'=>'HR',
            'bank'=>'Commercial Bank of Ceylon PLC',
            'bank_branch'=>'Thimbirigasyaya',
            'bank_number'=>'3116655229',
            'EPF_number'=>'87154ASDFRGLLD54ED',
            'next_kin_name'=>'Arjun Maniratnam',
            'next_kin_occupation'=>'Junior Operation Assistant',
            'next_kin_office_address'=>'Commercial Bank of Ceylon PLC,Maradana',
            'next_kin_phone_mobile'=>'0754898889',
            'next_kin_phone_home'=>'0114897689',
            'next_kin_address'=>'No:112,Fife road,Thimbirigasyaya,Colombo 03',
            'user_role'=>'employee',
            'supervisor_manager'=>'2',
            'created_at' => now(),
            'updated_at' => now()
        ]);
    
        DB::table('users')->insert([
            'avatar_id'=>null,
            'name' => 'Admin',
            'fname' => 'Admin',
            'mname' => 'Admin',
            'lname' => 'Admin',
            'email' => '18naduni@gmail.com',
            'password' => Hash::make('Secret&Secret'),
            'NIC'=>'905183991V',
            'current_job_position'=>'Admin',
            'phone_home'=>'0114896289',
            'phone_mobile'=>'0754896289',
            'address_permanent'=>'Admin',
            'branch'=>'Admin',
            'department'=>'HR',
            'bank'=>'Admin',
            'bank_branch'=>'Admin',
            'bank_number'=>'3006655429',
            'EPF_number'=>'87154ASDFRG511D54ED',
            'next_kin_name'=>'Admin',
            'next_kin_occupation'=>'Admin',
            'next_kin_office_address'=>'Admin',
            'next_kin_phone_mobile'=>'0754897289',
            'next_kin_phone_home'=>'0114896289',
            'next_kin_address'=>'Admin',
            'user_role'=>'admin',
            'supervisor_manager'=>'7',
            'created_at' => now(),
            'updated_at' => now()
        ]);
    }
}
